### ISSUE TITLE
SVG defaults

### ISSUE THREAD

**Issue by gjjones** [ebsco/edna#44]
The current sizing property use for SVGs does not produce the same results with PNGs. The result is large SVG representation when compared side by side to the PNG fallbacks.

``` CSS
[class*='svg-'] {
    ...
    background-size: 100%; /* This one */
}
```
