### ISSUE TITLE
Media Stylesheet

### ISSUE THREAD

**Issue by wylie** [ebsco/edna#88]
The `less/_media.less` stylesheet contains very little.

``` css
.img {
    a & {
        display: block;
    }
}
```

Can this, or should this, be removed/moved?
